export const NotificationType = {
  DUEL_INVITE: 'DUEL_INVITE',
  DUEL_RESULT: 'DUEL_RESULT',
  WEEKLY_EXAM_REMINDER: 'WEEKLY_EXAM_REMINDER',
  WEEKLY_EXAM_RESULT: 'WEEKLY_EXAM_RESULT',
  SCHOLARSHIP_EARNED: 'SCHOLARSHIP_EARNED',
  BADGE_EARNED: 'BADGE_EARNED',
  QUARANTINE_EXPIRY: 'QUARANTINE_EXPIRY',
  SHADOW_OPPONENT_DEFEATED: 'SHADOW_OPPONENT_DEFEATED',
} as const;

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];
